### ISSUE TITLE
A Minor Misspell

### ISSUE THREAD

**Issue by MinfangKang773773** [fenmeng123/SDPP_ABCD_TabDat#8]
Hi, I'm really impressed by your coding! However, I noticed a minor spelling error in line 148, SDPP_subfunctions.R

`>   fpirntf("|SDPP ParaSet| Some required R packageds have not been installed! Please see the table below:\n")`

There is a minor misspell 'fprintf' as 'fpirntf'. Other than that,it's excellent work!!!!!!!!

**Comment by fenmeng123** [comment]
Thanks for your notification. This typo will be addressed in the next submission.
